apiVersion: v1
entries:
  pgbouncer:
  - apiVersion: v2
    appVersion: latest
    created: "2025-09-28T17:02:54.06905+02:00"
    description: Pgbouncer helm chart for Kubernetes
    digest: 309550928c8d090e9094f5ad569f4b2c5b7d67ca141054166ef69d5276cab42b
    home: https://github.com/hansehe/postgres-helm
    icon: https://raw.githubusercontent.com/hansehe/postgres-helm/master/helm/postgres.png
    keywords:
    - postgres
    - pgbouncer
    maintainers:
    - email: hans.erik.heggem@gmail.com
      name: hansehe
    name: pgbouncer
    sources:
    - https://github.com/hansehe/postgres-helm
    type: application
    urls:
    - pgbouncer/pgbouncer-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v2
    appVersion: latest
    created: "2025-09-28T17:02:54.066925+02:00"
    description: Pgbouncer helm chart for Kubernetes
    digest: 6dd08b1dbcfbe40adac1d77a5815d6b0d699028c48367d1a1548ae532f29b1f4
    home: https://github.com/hansehe/postgres-helm
    icon: https://raw.githubusercontent.com/hansehe/postgres-helm/master/helm/postgres.png
    keywords:
    - postgres
    - pgbouncer
    maintainers:
    - email: hans.erik.heggem@gmail.com
      name: hansehe
    name: pgbouncer
    sources:
    - https://github.com/hansehe/postgres-helm
    type: application
    urls:
    - pgbouncer/pgbouncer-0.1.0.tgz
    version: 0.1.0
  postgres:
  - apiVersion: v2
    appVersion: "13.12"
    created: "2025-09-28T17:02:54.070532+02:00"
    description: Postgres helm chart for Kubernetes
    digest: 35a9a490ca8d903d5147cd2066f67596eae947ba473edd600e124ee1ce42c742
    home: https://github.com/hansehe/postgres-helm
    icon: https://raw.githubusercontent.com/hansehe/postgres-helm/master/helm/postgres.png
    keywords:
    - postgres
    maintainers:
    - email: hans.erik.heggem@gmail.com
      name: hansehe
    name: postgres
    sources:
    - https://github.com/hansehe/postgres-helm
    type: application
    urls:
    - postgres/postgres-0.1.0.tgz
    version: 0.1.0
generated: "2025-09-28T17:02:54.065339+02:00"
